# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [mrVenomYT]
patreon: DevVenom
ko_fi: # Replace with a single Ko-fi mrvenom
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.instagram.com/muhammad_hasil_13']
